spring.application.name=gonzoCards

spring.datasource.url=jdbc:postgresql://localhost:5432/gonzo_cards?useSSL=false&serverTimezone=UTC

spring.datasource.username=bestuser
spring.datasource.password=bestuser

spring.devtools.restart.enabled=true